### ISSUE TITLE
Implement `IntoIterator` for `RTree`

### ISSUE THREAD

**Issue by jakoschiko** [georust/rstar#113]
Currently
* `&RTree<T>` implements `IntoIterator<Item = &T>` and
* `&mut RTree<T>` implements `IntoIterator<Item = &mut T>`.

Would it be possible to also implement `IntoIterator<Item = T>` for `RTree<T>` (that will be consumed)?

I would be happy to help with a PR.

**Comment by urschrei** [comment]
Does https://docs.rs/rstar/0.10.0/rstar/struct.RTree.html#method.drain help for your use case?

**Comment by jakoschiko** [comment]
Yes, I'm currently using this. But it would still be nice to have an implementation of `IntoIterator<Item = T>` because this would improve the interoperability with other collection types.

Example:
```rust
let rtree: RTree<Rectangle> = todo!();
let vec: Vec<Rectangle> = rtree.into_iterator().collect();
```
