### ISSUE TITLE
Documentation about bulk load

### ISSUE THREAD

**Issue by jerabaul29** [georust/rstar#155]
https://github.com/georust/rstar/blob/c7d53c81b7588a66d2a3763937862311f73ab7bd/rstar/src/rtree.rs#L98-L101

```is still `O(log(n))```: should that not be ```is still `O(n log(n)) for inserting n points, though the scaling factor is significantly improved```?

**Comment by rmanoka** [comment]
Yes, the author probably meant O(log n) per element amortized.

**Comment by grovesNL** [comment]
@jerabaul29 looks like this is fixed now
