### ISSUE TITLE
Replace single `smallvec::SmallVec ` usage with `heapless::Vec`

### ISSUE THREAD

**Issue by frewsxcv** [georust/rstar#177]
https://docs.rs/heapless/0.8.0/heapless/struct.Vec.html 

We only use `SmallVec` in one place. What do we think about replacing that usage with `heapless`'s `Vec` so don't need the extra dep?

**Comment by adamreichold** [comment]
I don't this is easily possible. `SmallVec` will overflow onto the heap when the fixed capacity is exhausted where `heapless::Vec` does not. But there is not fixed upper bound on the capacity so iterators need AFAIU.

**Comment by frewsxcv** [comment]
You're totally right. Thanks for the info
