### ISSUE TITLE
Improve interoperability with other linear algebra crates

### ISSUE THREAD

**Issue by Stoeoef** [georust/rstar#28]
It would be nice if rstar had first class support for other geometry crates, e.g. `nalgebra` or `cgmath`.

Up to now, users either need to

- Implement their own point type (boiler plate / cannot easily use third-party point types due to orphan rule)
- Use the built in point type (like `[f64; 2]`, has only limited functionality)

One promising path forward might be adding support for the [mint crate](https://crates.io/crates/mint) crate. Adding `Point` impls for the mint types should allow to add them to an R-Tree directly. Both  `cgmath` and `nalgebra` support mint already.

This issue originated from #25

**Comment by ripytide** [comment]
Could this be closed as fixed with #134 now merged?

**Comment by adamreichold** [comment]
Agreed. Let's consider the `mint` support the canonical integration point as long as nobody asks for direct support of a particular crate like `nalgebra`.
