### ISSUE TITLE
Implement Point for Rc<dyn RTreeObject>

### ISSUE THREAD

**Issue by categulario** [georust/rstar#29]
Firsts of all thanks for this amazing crate. I'm already using it in two of my projects.

The problem I have is that I'd like to have my objects referenced through an Rc pointer while being inside the RTree but the compiler complains saying that:

`the trait bound `std::rc::Rc<shape::Shape>: rstar::point::Point` is not satisfied`

Without the Rc<_> it works perfectly. If you think this is something reasonable and can give me some advice I can even try to make a contribution ot this repo with that.

Thanks

**Comment by categulario** [comment]
I just realized that this might actually be the wrong question. I'll leave here just to see if there's a relevant comment to be made and eventually close it.

**Comment by rmanoka** [comment]
@categulario is this resolved?  Otherwise, could you provide a MWE explaining the issue / use-case?

**Comment by categulario** [comment]
I think I solved it in some other way.
