### ISSUE TITLE
Implement RTree::nearest_neighbors

### ISSUE THREAD

**Issue by jverce** [georust/rstar#30]
This API is present in the equivalent `RTree` struct in https://github.com/Stoeoef/spade.

**Comment by Stoeoef** [comment]
Thanks for opening the issue. I'm always interested to make rstar a true superset of spade's rtree features.
Just for clarification: You are referring to the [nearest_neighbors](https://docs.rs/spade/1.8.2/spade/rtree/struct.RTree.html#method.nearest_neighbors) method of spade?

This can already be implemented by downstream users with [nearest_neighbor_iter_with_distance](https://docs.rs/rstar/0.7.1/rstar/struct.RTree.html#method.nearest_neighbor_iter_with_distance), although a dedicated (and possibly more optimized) method for this feature is certainly possible.

Does this address your needs already? In any case, adding a `fn nearest_neighbors(...) -> impl Iterator<&T>` seens to be a good fit.

I should be able to get to this soon. If you want to work on this yourself let me know and I'll wait.

**Comment by jverce** [comment]
Yes, that's the method to which I'm referring. I'd like to take a stab at it if that's OK, unless there are reasons for you to implement it sooner.

**Comment by Stoeoef** [comment]
> I'd like to take a stab at it if that's OK, unless there are reasons for you to implement it sooner.

You are more than welcome to, thank you! Take your time.

Let me know if you are stuck. You can either go for the thin wrapper around `nearest_neighbor_iter_with_distance` or have a look at what spade does, which should be slightly more optimized.
The optimization that spade performs is *min distance pruning*; that is, nodes can be skipped if every point in them will be further away then the currently found best candidate. The same optimization is also performed for the (single) `nearest_neighbor` implementation in `rstar`.

In any case, I'll accept either solution, with or without min distance pruning.

**Comment by jverce** [comment]
Just checking in, I didn't forget about this but I've been super busy. Hopefully I should have more time in the next few weeks and I'll get to this :)

**Comment by OvermindDL1** [comment]
Was this just fixed in #49?  :-)

**Comment by jverce** [comment]
@OvermindDL1 yes! Closing the issue now, sorry, I forgot 😊
