### ISSUE TITLE
Call to RTree::bulk_load leads to "version `GLIBC_2.27' not found"

### ISSUE THREAD

**Issue by obeah** [georust/rstar#33]
Hi,

thank you for this great library.
I encountered an issue while testing on older Linux machine. 
**Short version**: everything works fine on the machine where I build release but when I test on the machine with older Linux I get an error:
 "version `GLIBC_2.27' not found"
By commenting out the code I identified that the problem appears only if I call **RTree::bulk_load**. Calling insted **RTree::new()** followed by **tree.insert()** calls eliminated the error.

**Details:**
1. I'm building a dynamic library (cdylib) which is called from java
2. ldd --version on build machine returns:
> ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27
3. ldd --version on test machine:
> ldd (Ubuntu GLIBC 2.23-0ubuntu7) 2.23
4. While trying to call .so library from java through JNA on the test machine I get the error:
> java.lang.UnsatisfiedLinkError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/user/dev/project1/resources/libtest.so)

Tried with stable rust 1.42 and 1.43, target x86_64-unknown-linux-gnu

I'm not sure if any other details may be necessary. I definitely isolated this issue to single line with bulk_load call.

**Comment by urschrei** [comment]
AFAIK this isn't an RStar issue, but a linker issue – if your target machine has 2.23, you'll need to build on a machine (or in a Docker container, using [`Cross`](https://github.com/rust-embedded/cross)) with 2.23 (or earlier). You may not need `Cross` if you can build your library on e.g. Travis; Trusty (14.04.6 LTS) is on libc 2.19, so that would also work as a lowest common denominator.

**Comment by rmanoka** [comment]
Agree with @urschrei .  @obeah could you please verify if the issue is relevant to this crate, and close this issue if not?

**Comment by obeah** [comment]
You are right, this is definitely not an RStar problem. Thank you. Closing the issue.
