### ISSUE TITLE
RectangleWithData?

### ISSUE THREAD

**Issue by Voker57** [georust/rstar#56]
Would be nice to have a RectangleWithData object, otherwise rectangle areas involve mostly reimplementing Rectangle.
Also, why not store data in RTree without requiring a type to support it?

**Comment by jblindsay** [comment]
I would ask for the same thing for the Line primitive. LineWithData as part of the library would be immensely helpful. I have spent the better part of a day trying to implement this myself without any luck. In many cases, having the rtree store geometries without some metadata will not work, e.g. if you want to link the geometries to some attribute data. Please consider adding RectangleWithData (which I have been able to implement on my own, but it feels very hacky) and LineWithData (which I have so far been unable to implement on my own) in the same way that you have implemented PointWithData. Thank you.

**Comment by urschrei** [comment]
Given the relatively slow pace of development that rstar currently sees, and the (at first glance) straightforward implementation of PointWithData (rstar/src/primitives/point_with_data.rs), could I gently encourage you to write it yourself and submit a PR, @jblindsay? We here at georust are stretched thin and are just about managing to stay on top of library maintenance, leaving little time for greenfield feature development at the moment. That having been said, there are a number of people who will briskly shepherd a PR along, and I'm very happy to commit to cutting a new release the moment it lands.

**Comment by jblindsay** [comment]
@urschrei No problem, I've already written it and you can expect a PR in the next few days. It was much easier writing this as part of the primitives than it is trying to write it outside of the library.

**Comment by urschrei** [comment]
Excellent. Thank you!

**Comment by jblindsay** [comment]
I've just made the pull request now.

**Comment by rmanoka** [comment]
Linking comment about generic container from the PR thread: https://github.com/georust/rstar/pull/73#issuecomment-890396060

Could folks interested in this issue kindly comment on the ergonomics of a generic container (as mentioned in the comment)?

**Comment by urschrei** [comment]
@rmanoka I've done some work on a generic container based on your ideas in the PR – I'll need some feedback / ideas on getters and setters if you've got some time this week? Would also be interesting to see whether we could re-implement PointWithData on top of it (before deprecating it?), but that's more of a nice-to-have.

**Comment by urschrei** [comment]
Closed by #74
