### ISSUE TITLE
Release 0.9.0

### ISSUE THREAD

**Issue by rmanoka** [georust/rstar#71]
@urschrei @michaelkirk I see you have made many clean-ups, and polishes leading up-to a release, but haven't released yet.  Should we release a version 0.9.0 in the next couple days?  I couldn't find a checklist for it, so jotting down the steps here:

- [x] Check `rstar/CHANGELOG.md` and ensure fixed issues are referenced, and closed
- [x] Publish `rstar` to crates.io
- [x] Create and push a tag marking released version

Anything else to be done?

closes #53

**Comment by urschrei** [comment]
Hi @rmanoka, yes let's do it. Your todo list is complete AFAIK — nothing else required.

**Comment by rmanoka** [comment]
Version 0.9.0 released to crates.

**Comment by michaelkirk** [comment]
Thanks for taking care of this @rmanoka!
