### ISSUE TITLE
Crates.io still refers to Stoeoef/rstar

### ISSUE THREAD

**Issue by nicholas-l** [georust/rstar#79]
The repository on https://crates.io/crates/rstar refers to https://github.com/Stoeoef/rstar rather than https://github.com/georust/rstar. It looks like all references to the old repo are updated in this repo so I assume that crates.io has to be updated through crates.io itself.
Also it seems that dependabot uses this information which also points users to `Stoeoef/rstar` rather than `georust/rstart`.

**Comment by michaelkirk** [comment]
Thanks for bringing this to our attention.

I assumed it would automatically update when we published new versions, but I guess not.

I poked around on crates.io and couldn't find any controls to do this manually.

I've just emailed crates.io support and will update with any response.

**Comment by michaelkirk** [comment]
Carol from crates.io has (quickly!) cracked the case.

> The value that appears on https://crates.io/crates/rstar for the repository is the *last published* metadata, not the *highest version number*. 
>
> I see the highest version number published is 0.9.2 which has the new `https://github.com/georust/rstar` value in the repository metadata, but after publishing that, 0.8.4 was published, and 0.8.4 has the old `https://github.com/Stoeoef/rstar` value in the repository metadata.
>
> If the next version you publish has the new repository URL and you don't publish any other versions with the old repository URL, it will get updated on crates.io.

So,  this will get solved with our next release.

**Comment by michaelkirk** [comment]
I've updated the Cargo.toml in our maintenance branch just in case we have another maintenance release on 0.8 and forget.

https://github.com/georust/rstar/blob/0.8_maintenance/rstar/Cargo.toml

**Comment by urschrei** [comment]
> I've updated the Cargo.toml in our maintenance branch just in case we have another maintenance release on 0.8 and forget.
> 
> 
> 
> https://github.com/georust/rstar/blob/0.8_maintenance/rstar/Cargo.toml

Ahh yes, this is all my fault. Thanks for catching it!
