### ISSUE TITLE
CI can't run because 1.51 treats the 2021 edition as unstable, and it's required by cargo-all-features

### ISSUE THREAD

**Issue by urschrei** [georust/rstar#94]
See e.g. https://github.com/georust/rstar/runs/6240513070?check_suite_focus=true

**Comment by jackson211** [comment]
I was running into the same issue a couple of days ago see #91.
I fixed it by setting cargo-all-features to 1.6.0 https://github.com/georust/rstar/pull/91/commits/4aecb80e49cc65d333e192605f44305b71ae6ad8

**Comment by rmanoka** [comment]
I merged that PR, so the issue is resolved?

**Comment by urschrei** [comment]
@rmanoka hmm maybe I need to pull the latest change, because CI is failing on https://github.com/georust/rstar/issues/92
